name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        xcode: ["13.4.1", "13.3.1"]
        include:
          - xcode: "13.4.1"
            macos: macOS-12
          - xcode: "13.3.1"
            macos: macOS-12
    runs-on: ${{ matrix.macos }}
    name: macOS
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Shows coverage file path
      run: swift test --show-codecov-path
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        fail_ci_if_error: true
        verbose: true
